tasks:
   - command: ./install-graphviz.sh && ./install-protobuf.sh && ./install-clif.sh && ./install-pyclif.sh && . .bashrc && git clone https://github.com/google/nucleus nucleus && cd nucleus && ./install.sh
