#image:
#  file: Dockerfile
tasks:
#  - command: . .bashrc && git clone https://github.com/google/protobuf ../protobuf && cd ../protobuf && ./autogen.sh && ./configure --prefix=$HOME && make -j 48 && make install
  - command: . .bashrc && cat xa* | tar xvfj - && if [ ! -f ../clif ]; then git clone https://github.com/google/clif ../clif; && cp clif.sh ../clif/INSTALL.sh && cd ../clif && ./INSTALL.sh; fi
  - command: . .bashrc && if [ ! -f ../nucleus ]; then git clone https://github.com/google/nucleus ../nucleus && cd ../nucleus && ./install.sh; fi
